<?php

return [
    ["libelle" =>"Accompagnement, Paramétrage et Formation (APF)", "employe_id" =>"2"],
    ["libelle" =>"Service logistique achats", "employe_id" =>"3"],
    ["libelle" =>"Architecture technique et infrastructure", "employe_id" =>"3"],
    ["libelle" =>"Service administration du personnel", "employe_id" =>"3"],
    ["libelle" =>"Secteur Appui méthodologique aux Projets GSI et Planification (APP)", "employe_id" =>"3"],
    ["libelle" =>"Bureau d'études", "employe_id" =>"3"],
    ["libelle" =>"Comité Directeur", "employe_id" =>"3"],
    ["libelle" =>"Communication", "employe_id" =>"3"],
    ["libelle" =>"Service comptabilité", "employe_id" =>"3"],
    ["libelle" =>"Conseil d'Administration", "employe_id" =>"3"],
    ["libelle" =>"Conseil médical", "employe_id" =>"3"],
    ["libelle" =>"Contrôle de gestion", "employe_id" =>"3"],
    ["libelle" =>"Direction générale", "employe_id" =>"3"],
    ["libelle" =>"Direction médicale", "employe_id" =>"3"],
    ["libelle" =>"Comité d'Éthique Hospitalo-Facultaire Universitaire de Liège", "employe_id" =>"3"],
    ["libelle" =>"Service exploitation des données RH", "employe_id" =>"3"],
    ["libelle" =>"Département financier", "employe_id" =>"3"],
    ["libelle" =>"Département gestion des ressources humaines", "employe_id" =>"3"],
    ["libelle" =>"Gestion des séjours patients", "employe_id" =>"3"],
    ["libelle" =>"Gestion du Système d'Information (GSI)", "employe_id" =>"3"],
    ["libelle" =>"Hygiène Hospitalière", "employe_id" =>"3"],
    ["libelle" =>"Service des informations médico économiques (SIME)", "employe_id" =>"3"],
    ["libelle" =>"Service juridique", "employe_id" =>"3"],
    ["libelle" =>"Département des services logistiques", "employe_id" =>"3"],
    ["libelle" =>"Service des marchés publics", "employe_id" =>"3"],
    ["libelle" =>"Pharmacie clinique", "employe_id" =>"3"],
    ["libelle" =>"Gestion de projets", "employe_id" =>"3"],
    ["libelle" =>"Psychologie clinique et action sociale", "employe_id" =>"3"],
    ["libelle" =>"Service recrutement et intégration", "employe_id" =>"3"],
    ["libelle" =>"Réclamations - facturation", "employe_id" =>"3"],
    ["libelle" =>"Département technique", "employe_id" =>"3"],
    ["libelle" =>"Service marketing et commercial", "employe_id" =>"3"],
    ["libelle" =>"Service de recherche et développement", "employe_id" =>"3"],
    ["libelle" =>"Service de production", "employe_id" =>"3"],
];