<?php

return [
    "Accompagnement, Paramétrage et Formation (APF)",
    "Service logistique achats",
    "Architecture technique et infrastructure",
    "Service administration du personnel",
    "Secteur Appui méthodologique aux Projets GSI et Planification (APP)",
    "Bureau d'études",
    "Comité Directeur",
    "Communication",
    "Service comptabilité",
    "Conseil d'Administration",
    "Conseil médical",
    "Contrôle de gestion",
    "Direction générale",
    "Direction médicale",
    "Comité d'Éthique Hospitalo-Facultaire Universitaire de Liège",
    "Service exploitation des données RH",
    "Département financier",
    "Département gestion des ressources humaines",
    "Gestion des séjours patients",
    "Gestion du Système d'Information (GSI)",
    "Hygiène Hospitalière",
    "Service des informations médico économiques (SIME)",
    "Service juridique",
    "Département des services logistiques",
    "Service des marchés publics",
    "Pharmacie clinique",
    "Gestion de projets",
    "Psychologie clinique et action sociale",
    "Service recrutement et intégration",
    "Réclamations - facturation",
    "Département technique",
    "Service marketing et commercial",
    "Service de recherche et développement",
    "Service de production",
];